spring.application.name=kentgozu
spring.ai.google.genai.api-key=AIzaSyDNk7sNUhn0VaTWvdsuRjMMs4vaV1hCaz8
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0
spring.ai.google.genai.embedding.vertex-ai=false
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768